version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: react-router-dom
    versions:
      - 6.*
